export const FETCH_GRAPHS_DASHBOARD = "FETCH_GRAPHS_DASHBOARD";
export const LOADING_HANDLER_DASHBOARD = "LOADING_HANDLER_DASHBOARD";
export const SUCCESS_HANDLER_DASHBOARD = "SUCCESS_HANDLER_DASHBOARD";
export const ERROR_HANDLER_DASHBOARD = "ERROR_HANDLER_DASHBOARD";
export const UPDATE_REQUEST_HANDLER_DASHBOARD =
  "UPDATE_REQUEST_HANDLER_DASHBOARD";
export const UPDATE_SERVICES_HANDLER_DASHBOARD =
  "UPDATE_SERVICES_HANDLER_DASHBOARD";
export const FETCH_SERVICE_TABLE_REQUESTS = "FETCH_SERVICE_TABLE_REQUESTS";
export const SERVICE_REQUEST_TABLE = "SERVICE_REQUEST_TABLE";
export const DOWNLOAD_VERIFICATION_EXCEL_DATA =
  "DOWNLOAD_VERIFICATION_EXCEL_DATA";
export const DOWNLOAD_SERVICE_EXCEL_DATA = "DOWNLOAD_SERVICE_EXCEL_DATA";
export const UPDATE_GRAPH_HANDLER = "UPDATE_GRAPH_HANDLER";
export const SEND_FORGOT_EMAIL_LOGIN = "SEND_FORGOT_EMAIL_LOGIN";
export const LOADING_HANDLER_LOGIN = "LOADING_HANDLER_LOGIN";
export const ERROR_HANDLER_LOGIN = "ERROR_HANDLER_LOGIN";
export const RESET_LOGIN = "RESET_LOGIN";

export const FETCH_STATISTICS = "FETCH_STATISTICS";
export const LOADING_HANDLER_STATISTICS = "LOADING_HANDLER_STATISTICS";
export const ERROR_HANDLER_STATISTICS = "ERROR_HANDLER_STATISTICS";
export const FETCH_MAP_REQUESTS = "FETCH_MAP_REQUESTS";

export const FETCH_MAYORS_REQUEST = "FETCH_MAYORS_REQUEST";
